### PR TITLE
Proofreading of comments

### PR DESCRIPTION
**Pull request by PeterJRiches**
Hi,
Thank you for making this project! In looking at the code to find out how it works, I found some errors in the documentation/comments (mostly typos and cases where the comments were less up-to-date than the code) and I offer these potential corrections for your approval.

I can't find fault with the executable code, and I'm going to install it on my machine.
Warmly,
Pete

### CODE REVIEW

**Comment by PeterJRiches** [comment]
By the way, this is my first pull request, so please be gentle. ;)

**Comment by andresgongora** [comment]
Wow! Thanks so much! Indeed, we work on the comments but never really revise them. Also, probably none of the contributors we had so far are native english speaking, so you help is extremely welcome. I'm merging now and also adding you to the authors file!

**Comment by andresgongora** [comment]
I've just updated the AUTHORS.md file. Feel free to edit any way you like (e.g. add your email or change the summary of your explanation however you like ;) )

**Comment by andresgongora** [comment]
Oh! I forgot to say! If you have any feature requests, or want to contribute with new ones you implement yourself, feel free to open as many issues/pull-requests as needed. Open software lives and evolves from the cooperation of many :)

I haven't really gotten around to the latest of them yet. But all open issues reflect more-less our next steps... although some are really optional and are always "left for another moment" hehehe

**Pull request merged**
